-- ==============================================================================
-- SQL DDL SCHEMA UNTUK SUPABASE SQL EDITOR
-- Sistem Manajemen Siswa Les Privat Coding
-- ==============================================================================

-- 1. TABEL: students
CREATE TABLE IF NOT EXISTS public.students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_code VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    age_level VARCHAR(255),
    parent_email VARCHAR(255),
    programming_lang VARCHAR(255) DEFAULT 'Python',
    schedule_notes VARCHAR(255) DEFAULT 'Fleksibel',
    learning_system VARCHAR(50) CHECK (learning_system IN ('Paket', 'Bulanan')) DEFAULT 'Paket',
    package_quota INT DEFAULT 8,
    status VARCHAR(50) CHECK (status IN ('Aktif', 'Cuti', 'Lulus')) DEFAULT 'Aktif',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. TABEL: meeting_logs
CREATE TABLE IF NOT EXISTS public.meeting_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    meeting_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    session_number INT DEFAULT 1,
    topic VARCHAR(255) NOT NULL,
    project_progress VARCHAR(255),
    rating INT CHECK (rating BETWEEN 1 AND 5) DEFAULT 5,
    evaluation_notes TEXT,
    attendance_status VARCHAR(50) CHECK (attendance_status IN ('Hadir', 'Izin', 'Alfa')) DEFAULT 'Hadir',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. TABEL: payments
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    package_period VARCHAR(255) NOT NULL,
    amount NUMERIC(12, 2) DEFAULT 0.00,
    transfer_method VARCHAR(255) DEFAULT 'BCA',
    payment_status VARCHAR(50) CHECK (payment_status IN ('Lunas', 'Belum Bayar')) DEFAULT 'Belum Bayar',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. DATA AWOAL / SAMPLE DATA
INSERT INTO public.students (student_code, name, age_level, parent_email, programming_lang, schedule_notes, learning_system, package_quota, status)
VALUES 
  ('COD-001', 'Budi Santoso', 'SMP Kelas 8', 'budi.ortu@email.com', 'Python', 'Fleksibel', 'Paket', 8, 'Aktif'),
  ('COD-002', 'Siti Rahma', 'SMA Kelas 10', 'siti.ortu@email.com', 'Web Dev (HTML/CSS/JS)', 'Fleksibel', 'Bulanan', 0, 'Aktif')
ON CONFLICT (student_code) DO NOTHING;

INSERT INTO public.meeting_logs (student_id, meeting_date, session_number, topic, project_progress, rating, evaluation_notes, attendance_status)
VALUES 
  (1, CURRENT_TIMESTAMP, 1, 'Pengenalan Variable & Data Type Python', 'Membuat Kalkulator Sederhana', 4, 'Sangat antusias, cepat paham', 'Hadir')
ON CONFLICT DO NOTHING;

INSERT INTO public.payments (student_id, payment_date, package_period, amount, transfer_method, payment_status)
VALUES 
  (1, CURRENT_DATE, 'Paket 8 Sesi', 1200000, 'BCA', 'Lunas'),
  (2, CURRENT_DATE, 'Bulan Juli 2026', 600000, 'Mandiri', 'Belum Bayar')
ON CONFLICT DO NOTHING;
